#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import csv
import sys
import shutil
from typing import Any, List, Dict, Optional, Set, Tuple

import pandas as pd
import networkx as nx

try:
	from SchemaAnnotation import consolidate
	from utils import (core_functions as cof,
						clustering_functions as cf,
										file_functions as ff,
										alignments_functions as af,
										sequence_functions as sf,
										iterable_functions as itf,
										blast_functions as bf,
										linux_functions as lf,
										classify_cds_functions as ccf,
										constants as ct,
										print_functions as pf)
except ModuleNotFoundError:
	from SchemaRefinery.SchemaAnnotation import consolidate
	from SchemaRefinery.utils import (core_functions as cof,
										clustering_functions as cf,
										file_functions as ff,
										alignments_functions as af,
										sequence_functions as sf,
										iterable_functions as itf,
										blast_functions as bf,
										linux_functions as lf,
										classify_cds_functions as ccf,
										constants as ct,
										print_functions as pf)


def determine_common_loci_ids(schema_directories):
	"""
	Determine the set of common loci identifiers between the input schemas.

	Parameters
	----------
	schema_directories : List[str]
		List of paths to the input schema directories.

	Returns
	-------
	common_loci : Set[str]
		Set of common loci identifiers between the input schemas.
	"""
	common_loci = set()
	# Get list of files for the first schema
	schemas_files = [set([ff.file_basename(file, False) for file in ff.get_paths_in_directory_with_suffix(schema_directories[0], ".fasta")])]
	for schema in schema_directories[1:]:
		# Get the list of files for the other schemas and determine if they have loci identifers in common with previous schemas
		current_schema_files = set([ff.file_basename(file, False) for file in ff.get_paths_in_directory_with_suffix(schema, ".fasta")])
		for i, file_set in enumerate(schemas_files):
			common_loci_ids = set.intersection(file_set, current_schema_files)
			if len(common_loci_ids) > 0:
				pf.print_message(f"The input schemas in {schema_directories[i]} and {schema} have the following loci identifiers in common: {', '.join(common_loci_ids)}", "info")
				common_loci.update(common_loci_ids)
		schemas_files.append(current_schema_files)

	return common_loci


def compute_cds_frequency(input_fasta, temp_directory):
	"""
	Compute the CDS frequency in the genomes.

	Parameters
	----------
	input_fasta : str
		Path to the input FASTA file containing CDSs.
	temp_directory : str
		Path to the temp folder created by chewBBACA's AlleleCall
		module when the `--no-cleanup` option is provided. The
		function uses this path to access the file with the encoded
		CDS genome presence data created by chewBBACA.

	Returns
	-------
	frequencies : Dict[str, int]
		Dictionary with CDS identifiers as keys and the frequency of
		the CDSs in the genomes as values.
 	"""
	# Import CDSs (sequence IDs as keys and sequences as values)
	cds_sequences = sf.fetch_fasta_dict(input_fasta)
	# Count the frequency of CDSs in the genomes and identify their presence
	# Read the file with the CDS genome presence data created by chewBBACA
	cds_presence: str = ff.join_paths(temp_directory, [ct.CDS_HASHTABLE_PATH])
	# Decode the data
	decoded_seqids: Dict[str, List[float]] = itf.decode_CDS_sequences_ids(cds_presence)
	# The CDSs and the decoded sequence IDs need to come from the same run
	# Each CDS must have a corresponding hash in the decoded sequence IDs
	frequencies: Dict[str, int] = {}
	for seqid, sequence in cds_sequences.items():
		hashed_seq: str = sf.seq_to_hash(str(sequence))
		# Count only the unique genome IDs for the frequency [1:]
		frequencies[seqid] = len(set(decoded_seqids[hashed_seq][1:]))

	return frequencies


def compute_class_counts(input_directory):
	"""
	Compute the loci class counts and frequency based on the profiles determined by chewBBACA.

	Parameters
	----------
	input_directory : str
		Path to a folder containing allele calling results generated with chewBBACA.

	Returns
	-------
	classification_percentages : Dict[str, List[List[int] | float | int]]
		Dictionary with locus identifiers as keys and a list of the class
		counts, the percentage of special classifications, and the frequency
		of the locus in the genomes as values.
	"""
	# Read the profiles file generated by chewBBACA
	profiles_file = ff.join_paths(input_directory, [ct.PROFILES_FILENAME])
	profiles = pd.read_csv(profiles_file, sep = '\t', dtype = object)
	# Determine the number of total genomes in the dataset
	total_genomes = len(profiles["FILE"])
	loci_ids = profiles.columns[1:]
	classification_percentages = {}
	# Compute the values for each locus
	for locus in loci_ids:
		locus_column = profiles[locus]
		# Remove "INF-" prefixes
		masked_column: pd.Series = locus_column.str.replace('INF-', '')
		# Convert exact matches to 1
		masked_column: pd.Series = locus_column.map(lambda x: 1 if str(x) not in ct.CHEWIE_CLASSES else x)
		class_counts = masked_column.value_counts()
		# Determine percentage of special classifications and exact matches
		class_counts = [int(class_counts.get(c, 0)) for c in ct.CHEWIE_CLASSES] + [class_counts.get(1, 0)]
		# Do not include LNF classifications and exact matches
		special_percentage = round(sum(class_counts[:-2])/total_genomes, 3)
		# Determine frequency
		# Consider PLOT5/PLOT3/LOTSC and NIPH/NIPHEM classes as presence
		locus_frequency = sum(class_counts[2:7]+[class_counts[-1]])
		classification_percentages[locus] = [class_counts, special_percentage, locus_frequency]

	return classification_percentages


def read_blast_results(input_file, filter_criteria=None):
	"""
	Read BLAST results from a TSV file (--outfmt 6).

	Parameters
	----------
	input_file : str
		Path to the input file containing BLAST results in tabular format.

	Returns
	-------
	blast_data : Dict[Tuple[str, str], List[List[str]]]
		Dictionary with query-subject pairs as keys and a list of lists
		containing the BLAST match data for each HSP as values.
	"""
	# Read file with BLAST results
	with open(input_file, 'r') as infile:
		# Each line contains the following values: qseqid sseqid qlen slen qstart qend sstart send length score gaps pident
		blast_lines = list(csv.reader(infile, delimiter='\t'))
		# Filter results based on criteria

#########################

		# Create dictionary with QS pairs as keys
		blast_data = {}
		if blast_lines:
			# Group all HSPSs for the same QS pair
			for line in blast_lines:
				blast_data.setdefault((line[0], line[1]), []).append(line[2:])
	
	return blast_data


def compute_global_stats(query, subject, frequencies, blastp_data, blastn_data):
	"""
	Compute global statistics for a query-subject pair alignemnt.

	Parameters
	----------
	query : str
		Query sequence identifier.
	subject : str
		Subject sequence identifier.
	frequencies : Dict[str, int]
		Dictionary with sequence identifiers as keys and their frequency in the genomes as values.
	blastp_data : List[List[str]]
		List of lists containing the BLASTp match data for each HSP.
	blastn_data : List[List[str]]
		List of lists containing the BLASTn match data for each HSP.
	"""
	# Get query and subject frequency values to the line
	# Use the seqid in the BLAST output files if running in the "cds" mode
	# Determine the locus identifier otherwise
	query_frequency = frequencies[query] if query in frequencies else frequencies[query.rsplit('_', 1)[0]]
	subject_frequency = frequencies[subject] if subject in frequencies else frequencies[subject.rsplit('_', 1)[0]]

	# Calculate the frequency ratio
	# The frequency of the query or subject should not be 0 because of the frequency threshold initially applied
	# which should remove all sequences with a frequency of 0
	frequency_ratio = round(min(query_frequency/subject_frequency, subject_frequency/query_frequency), 3)

	# Get the sequence length for the query and subject
	# Need to get sequence length value from BLASTn matches if there were no BLASTp matches
	if blastp_data:
		query_len = blastp_data[0][0]
		subject_len = blastp_data[0][1]
	else:
		query_len = str(int(int(blastn_data[0][0])/3))
		subject_len = str(int(int(blastn_data[0][1])/3))

	global_data = [query_len, subject_len, query_frequency, subject_frequency, frequency_ratio]

	return global_data


def compute_local_stats(match_data, query_sscore):
	"""
	Compute local statistics for a query-subject pair alignemnt based on the BLAST match data.

	Parameters
	----------
	match_data : List[str]
		List containing the BLAST match data for a single HSP.
	query_sscore : float
		BLAST Score Ratio for the alignment.

	Returns
	-------
	match_stats : List[float | List[int] | float]
		List containing the BSR value, the aligned intervals for the query and subject sequences, and the percent identity for the HSP.
	"""
	# Compute the BSR value for the HSP
	# The BSR is the ratio between the BLAST score of the alignment and the BLAST score of the query sequence against itself.
	# It is a measure of the similarity between the query and subject sequences, normalized by the self-similarity of the query sequence.
	# A BSR value close to 1 indicates a high similarity between the query and subject sequences, while a BSR value close to 0 indicates a low similarity.
	bsr = None if query_sscore is None else round(float(match_data[7])/query_sscore, 3)
	# Get the length of the alignment (have to merge the length of the HSPs if there are multiple HSPs for the same QS pair later)
	query_aligned_interval = [int(match_data[2]), int(match_data[3])] if int(match_data[2]) < int(match_data[3]) else [int(match_data[3]), int(match_data[2])]
	subject_aligned_interval = [int(match_data[4]), int(match_data[5])] if int(match_data[4]) < int(match_data[5]) else [int(match_data[5]), int(match_data[4])]
	match_pident = float(match_data[9])
	match_stats = [bsr, query_aligned_interval, subject_aligned_interval, match_pident]

	return match_stats


def compute_class_stats(match_data, query_length, subject_length):
	"""
	Compute the statistics used to evaluate each query-subject pair and assign a class.

	Parameters
	----------
	match_data : List[List[str]]
		List of lists containing the BLAST match data for each HSP between a query-subject pair.
	query_length : int
		Length of the query sequence.
	subject_length : int
		Length of the subject sequence.

	Returns
	-------
	class_stats : List[float]
		List containing the global alignment minimum and maximum values, the global percent identity
		minimum and maximum values, and the maximum BSR value from all HSPs for the query-subject pair.
	"""
	class_stats = None
	# Get query aligned intervals
	query_aligned_intervals: List[int] = sorted([m[1] for m in match_data], key= lambda x: x[0])
	# It is possible that there are no matches if working with BLASTp results if the query and subject protein sequences are very different
	# This is usually caused by a frameshift mutation that causes a very different translation of the CDS sequence, which can be detected by BLASTn but not by BLASTp
	# No alignments at the BLASTn level are more common
	if len(query_aligned_intervals) > 0:
		# Merge BLAST aligned intervals
		# Query
		query_aligned_merged_intervals = af.merge_intervals(query_aligned_intervals)
		# Get the total aligned length for the query
		query_aligned_length = sum([(i[1]-i[0]) for i in query_aligned_merged_intervals])
		# Subject
		subject_aligned_intervals: List[int] = sorted([m[2] for m in match_data], key= lambda x: x[0])
		subject_aligned_merged_intervals = af.merge_intervals(subject_aligned_intervals)
		# Get the total aligned length for the subject
		subject_aligned_length = sum([(i[1]-i[0]) for i in subject_aligned_merged_intervals])
		# Compute the weighted pident based on the pident of all HSPSs
		# Different HSPSs can overlap and it is not possible to compute the true pident based on BLAST's tabular output
		query_aligned_identity: float = sum(float(m[3])*((m[1][1]-m[1][0])/query_length) for m in match_data)
		subject_aligned_identity: float = sum(float(m[3])*((m[2][1]-m[2][0])/subject_length) for m in match_data)
		# Compute the global palign minimum and maximum values
		# The global palign is the fraction of the query and subject sequences that align, which can be different
		# for the query and subject if they have different lengths and if the aligned regions are not the exactly
		# the same for the query-subject and subject-query alignments
		global_talign_min: float = min(query_aligned_length / query_length,
									subject_aligned_length / subject_length)
		global_talign_max: float = max(query_aligned_length / query_length,
									subject_aligned_length / subject_length)
		# Compute the minimum and maximum global percent identity
		global_pident_min: float = min(query_aligned_identity, subject_aligned_identity)
		global_pident_max: float = max(query_aligned_identity, subject_aligned_identity)
		# Get the maximum BSR value from all QS HSPSs
		# We cannot get a global BSR because the HSPs may overlap
		max_bsr: float = 0 if match_data[0][0] is None else max([m[0] for m in match_data])

		class_stats = [round(global_talign_min, 3), round(global_talign_max, 3),
					   round(global_pident_min, 3), round(global_pident_max, 3),
					   max_bsr]

	return class_stats


def assign_class(qs_data, galign_threshold, pident_threshold, bsr_threshold, frequency_ratio):
	"""
	Assign a class to a query-subject pair based on the computed statistics and predefined thresholds.

	Parameters
	----------
	qs_data : List[float]
		List containing the global alignment minimum and maximum values, the global percent identity
		minimum and maximum values, and the maximum BSR value from all HSPs for the query-subject pair.
	galign_threshold : float
		Threshold for the global aligned fraction value to consider an alignment as good.
	pident_threshold : float
		Threshold for the global percent identity value to consider an alignment as good.
	bsr_threshold : float
		Threshold for the BSR value to consider an alignment as good.
	frequency_ratio : float
		Ratio of query to subject frequency to determine which class to assign.

	Returns
	-------
	assigned_class : str
		Assigned class for the query-subject pair.
	"""
	if qs_data:
		# If the minimum global palign is >= than the threshold
		if qs_data[0] >= galign_threshold:
			# If the BSR of the best HSP is greater or equal to the threshold, assign class 1a (Join)
			if qs_data[4] >= bsr_threshold:
				assigned_class = '1a'
			# Otherwise, assign class 1b (Add/Drop) or 1c (Choice) based on the frequency ratio
			# Class 1b recommends that the sequence with the lower frequency is dropped and the most frequent is kept
			# Class 1c recommends that either sequence can be kept because they have similar frequency values or the user should choose which to drop and which to keep 
			else:
				assigned_class = '1b' if frequency_ratio <= 0.1 else '1c'
		# If the minimum global palign is between 0.4 and the threshold
		elif (0.4 <= qs_data[0] < galign_threshold):
			# If the maximum pident value is greater or equal to the threshold
			if qs_data[3] >= pident_threshold:
				# If the maximum global palign is greater or equal to the threshold, assing class 2a (Add/Drop) or 2b (Choice) based on the frequency ratio
				# Class 2a recommends that the sequence with the lower frequency is dropped and the most frequent is kept
				# Class 2b recommends that either sequence can be kept because they have similar frequency values or the user should choose which to drop and which to keep
				if qs_data[1] >= galign_threshold:
					assigned_class = '2a' if frequency_ratio <= 0.1 else '2b'
				# If the maximum global palign is less than the threshold, assign class 3a (Add/Drop) or 3b (Choice) based on the frequency ratio
				# Again, users can choose which sequence to keep and which to drop if the frequency values are similar or they can choose to drop the sequence with the lower frequency and keep the most frequent one
				else:
					assigned_class = '3a' if frequency_ratio <= 0.1 else '3b'
			# If the maximum pident value is less than the threshold, assign class 4a (Add/Drop), 4b (Choice), or 4c (Add) based on the maximum global palign and frequency ratio values
			else:
				if qs_data[1] >= galign_threshold:
					assigned_class = '4a' if frequency_ratio <= 0.1 else '4b'
				else:
					assigned_class = '4c'
		# Assign class 5 (Add) if the minimum global palign is less than 0.4 because the query and subject sequences are very different or one is smaller and aligns well/is contained in the other
		else:
			assigned_class = '5'
	# Assign class 6 when there were no matches with BLASTp but there were with BLASTn
	# This can be caused by frameshift mutations that cause very different translations of the CDS sequences, which can be detected by BLASTn but not by BLASTp
	else:
		assigned_class = '6'

	return assigned_class


def write_matches_data(matches_data, output_file):
	"""
	Write the output file with information for all query-subject matches.

	Parameters
	----------
	matches_data : Dict[Tuple[str, str], List[List | List | List[float]]]
		Dictionary with query-subject pairs as keys and a list of lists containing the match data
		the query-subject alignments, the subject-query alignments, and the global data for the
		query-subject pair as values.
	output_file : str
		Path to the output file where the match data will be written.

	Returns
	-------
	int
		The number of lines/matches written to the output file (excluding the header).
	"""
	# Write output file with information for all matches
	match_data_lines = [ct.MATCHES_HEADER]
	for qs_pair, match_data in matches_data.items():
		query, subject = qs_pair
		global_data = match_data[2]
		query_class = match_data[0][-1]
		subject_class = match_data[1][-1]
		query_blastp_data = match_data[0][-3] if match_data[0][-3] is not None else ["NA"]*5
		subject_blastp_data = match_data[1][-3] if match_data[1][-3] is not None else ["NA"]*5
		query_blastn_data = match_data[0][-2][:-1] if match_data[0][-2] is not None else ["NA"]*4
		subject_blastn_data = match_data[1][-2][:-1] if match_data[1][-2] is not None else ["NA"]*4

		# Merge values into a single list
		qs_pair_data = [query, subject] + list(map(str, global_data)) + [query_class, subject_class] + list(map(str, query_blastp_data)) + list(map(str, subject_blastp_data)) + list(map(str, query_blastn_data)) + list(map(str, subject_blastn_data))
		match_data_lines.append(qs_pair_data)

	match_data_outlines = ["\t".join(line) for line in match_data_lines]
	with open(output_file, "w") as outfile:
		outfile.write("\n".join(match_data_outlines)+"\n")

	# Return the number of lines/matches written to the output file (excluding the header)
	return len(match_data_outlines)-1


def assign_action(classes, class_order):
	"""
	Assigns an action based on the order of precendence for classes and on the query and subject frequencies.

	Parameters
	----------
	classes : List[Tuple[str, int, int]]
		List of tuples containing the class, query frequency, and subject frequency.
	class_order : Dict[str, int]
		Dictionary mapping classes to their order of precedence.

	Returns
	-------
	assigned_action: Tuple[str, str]
		The assigned action and top class.
	"""
	sorted_classes = sorted(classes, key=lambda x: class_order.get(x[0]))
	top_class, query_frequency, subject_frequency = sorted_classes[0]
	# Assign action based on top/highest class
	if top_class == '1a':
		assigned_action = ("Join", top_class)
	elif top_class in {'1b', '2a', '3a', '4a'}:
		# Need query and subject frequencies to decide which to drop
		# If the query frequency is higher than the subject frequency, the subject sequence is dropped and the query sequence is kept, and vice versa
		if query_frequency > subject_frequency:
			assigned_action = ("Add", top_class)
		elif subject_frequency > query_frequency:
			assigned_action = ("Drop", top_class)
	# Classes 1c, 2b, 3b, and 4b are Choice because they can be somewhat similar and have comparable frequencies
	# It is important for users to evaluate these cases carefully and decide which sequence to keep and which to drop
	# Class 6 is also Choice because it can be caused by frameshift mutations and should be evaluated and excluded if they really correspond to frameshifts
	elif top_class in {'1c', '2b', '3b', '4b', '6'}:
		assigned_action = ("Choice", top_class)
	# Classes 4c and 5 are Add because the sequences are quite different and the most likely scenario is that they correspond to different loci
	else:
		assigned_action = ("Add", top_class)

	return assigned_action


def determine_groups(qs_pairs, assigned_actions, run_mode):
	"""
	Determines the groups of sequences and actions to be included in the output file with the recommendations.

	Parameters
	----------
	qs_pairs : List[Tuple[str, str]]
		List of query-subject pairs/edges used to create the graph.
	assigned_actions : Dict[str, Tuple[str, str]]
		Dictionary mapping sequence IDs to their assigned actions and top classes.
	run_mode : str
		Mode of running the process ("schema" or "cds").

	Returns
	-------
	groups : List[List[Tuple[str, str, str]]]
		List of lists containing the groups of sequences and their assigned actions and top classes.
	groups_seqids : Set[str]
		Set of all representative sequence IDs.
	"""
	# Create graph with QS pairs as edges
	G = nx.Graph()
	G.add_edges_from(qs_pairs)
	# Get the connected components of the graph, which correspond to groups of sequences that are connected by the QS pairs
	connected_components: List[Set[str]] = list(nx.connected_components(G))
	# Sort components by decreasing size
	connected_components = sorted(connected_components, key=lambda x: len(x), reverse=True)
	# Process each connected component to create the groups
	groups = []
	# Store all representative seqids
	groups_seqids = set()
	for cc in connected_components:
		# Need to get the locus identifiers from the allele IDs if running in the "schema" mode
		if run_mode == "schema":
			seqids = set([seqid.rsplit('_', 1)[0] for seqid in cc])
		# In the "cds" mode, the seqids in the BLAST output files already correspond to the CDS identifiers
		else:
			seqids = cc

		# Store the sequence ID, assigned action, and top class for each sequence in the group
		current_group = [(seqid, *assigned_actions[seqid]) for seqid in seqids]
		groups.append(current_group)
		groups_seqids.update(seqids)

	return [groups, groups_seqids]


def write_recommendations(groups, output_file):
	"""
	Write the output file with the recommendations.

	Parameters
	----------
	groups : List[List[Tuple[str, str, str]]]
		List of lists containing the groups of sequences and their assigned actions and top classes.
	output_file : str
		Path to the output file.

	Returns
	-------
	List[int]
		List containing the number of groups and total recommendations written to the output file.
	"""
	outlines = [ct.RECOMMENDATIONS_HEADER]
	i = 1
	total_recommendations = 0
	for g in groups:
		# Add group number
		outlines.append(f"#{i}")
		lines = ["\t".join(a) for a in g]
		total_recommendations += len(lines)
		outlines.extend(lines)
		i += 1

	outtext = "\n".join(outlines)
	with open(output_file, "w") as outfile:
		outfile.write(outtext+"\n")

	# The last increment to i is not assigned to any group, so the number of groups is i-1
	return [i-1, total_recommendations]


def count_action_class_pairs(groups):
	"""
	Count the number of times each action-class pair appears in the groups.

	Parameters
	----------
	groups : List[List[Tuple[str, str, str]]]
		List of lists containing the groups of sequences and their assigned actions and top classes.

	Returns
	-------
	action_counts : Dict[Tuple[str, str], int]
		Dictionary mapping action-class pairs to their frequencies.
	"""
	action_counts = {}
	for g in groups:
		actions = [(a[1], a[2]) for a in g]
		for a in actions:
			if a in action_counts:
				action_counts[a] += 1
			else:
				action_counts[a] = 1

	return action_counts


def refine_schema(input_schemas: List[str], allelecall_directories: List[str], output_directory: str,
				  annotations: str, constants: List[Any], run_mode: str, cpu: int, no_cleanup: bool) -> None:
	"""
	Evaluates the loci in the input schemas or the CDSs in a FASTA file to determine actions to create a refined schema.

	Parameters
	----------
	input_schemas : List[str]
		List of paths to schemas.
	output_directory : str
		Path to the output directory.
	allelecall_directories : List[str]
		Path to the folders containing the allele calling results generated with chewBBACA for each of the input schemas.
		The results in each folder must match the same dataset and be passed in the same order as the input schemas.
	annotations : str
		Path to a TSV file containing loci annotations.
	constants : List[Any]
		List of parameter values used throughout the process.
	run_mode : str
		Run mode for the process ("schema" or "cds").
	cpu : int
		Number of CPUs to use.
	no_cleanup : bool
		Flag to indicate whether to clean up temporary files.

	Returns
	-------
	None
	"""
	# Create base output directory
	ff.create_directory(output_directory)
	# Create initial processing output directory based on run mode
	processed_indata: str = os.path.join(output_directory, '1_Input_Data')
	ff.create_directory(processed_indata)
	# Create folder to store BLAST inputs
	blast_inputs = os.path.join(output_directory, "2_BLAST_Inputs")
	ff.create_directory(blast_inputs)
	# Set the minimum number of genomes in which a CDS cluster should be present to be kept in the analysis
	# Set to >=2% or 0 if dataset has less than 26 genomes
	if not constants[2]:
		pf.print_message("Setting value for the minimum number of genomes a representative CDS/locus should be present in...", "info")
		# The allele call results must be for the same dataset
		constants[2] = ccf.set_minimum_genomes_threshold(allelecall_directories[0], constants[2])
		pf.print_message(f"Set genome presence threshold to {constants[2]}.", "info")

	# Get Path to the BLAST executables
	makeblastdb_exec: str = lf.get_tool_path('makeblastdb')
	blastn_exec: str = lf.get_tool_path('blastn')
	blastp_exec: str = lf.get_tool_path('blastp')
	blastdb_aliastool_exec: str = lf.get_tool_path('blastdb_aliastool')

	excluded = {}
	if run_mode == 'cds':
		# Copy file with the unclassified CDSs to the initial processing output directory
		pf.print_message(f"Copying FASTA file with input CDSs to {processed_indata}...", "info")
		cds_sequences_src: str = os.path.join(allelecall_directories[0], "unclassified_sequences.fasta")
		cds_sequences_dest = shutil.copy(cds_sequences_src, processed_indata)
		# Define the path to the temp folder with the intermediate files from AlleleCall
		temp_folder: str = os.path.join(allelecall_directories[0], 'temp')
		# Calculate the frequency of the CDSs in the genomes
		pf.print_message("Computing the frequency of the CDSs in the genomes...", "info")
		cds_frequency = compute_cds_frequency(cds_sequences_dest, temp_folder)

		# Exclude CDSs shorter than size threshold
		pf.print_message(f"Excluding CDSs shorter than {constants[6]} bp...", "info")
		cds_sequences = sf.fetch_fasta_dict(cds_sequences_dest)
		cds_sequences, short = ccf.filter_by_size(cds_sequences, constants[6])
		for seqid in short:
			excluded.setdefault(seqid, []).append(f"Short")

		pf.print_message(f"{len(cds_sequences)}/{len(cds_frequency)} CDSs have size greater or equal to {constants[6]} bp.", 'info')

		pf.print_message("Translating and deduplicating the CDSs...", "info")
		# Translate and deduplicate the CDSs
		# The protein_sequences contains only the distinct sequences
		protein_sequences, _ = sf.translate_seq_deduplicate(cds_sequences, processed_indata, constants[6], constants[7], True)

		pf.print_message("Clustering the translated distinct CDSs...", "info")
		# Sort proteins by size before clustering
		protein_sequences = {k: v for k, v in sorted(protein_sequences.items(), key=lambda x: len(x[1]), reverse=True)}
		# Run minimizer-based clustering
		reps_groups: Dict[str, List[str]] = {}
		clusters: Dict[str, List[str]] = {}
		reps_sequences: Dict[str, str] = {}
		prot_len_dict: Dict[str, int] = {}
		clusters, reps_sequences, reps_groups, prot_len_dict = cf.minimizer_clustering(
			protein_sequences,
			clusters,
			reps_sequences,
			reps_groups,
			clustering_sim=constants[4],
			clustering_cov=constants[5],
			size_threshold = constants[9],
			grow = True)

		# Reformat clusters to contain only representative IDs as keys and a list of CDS IDs as values
		clusters = {repid: [m[0] for m in members] for repid, members in clusters.items()}

		# Determine the total number of clusters
		total_clusters: int = len(clusters)
		pf.print_message(f"Clustered {len(protein_sequences)} distinct proteins into {total_clusters} clusters.", "info")

		# Determine the number of singleton clusters
		singletons: int = len([cluster for cluster in clusters.values() if len(cluster) == 1])
		pf.print_message(f"{total_clusters - singletons} clusters contain more than one CDS.", "info")
		pf.print_message(f"{singletons} clusters are singletons.", "info")

		pf.print_message(f"Excluding clusters based on the frequency of the CDSs in the genomes (<={constants[2]})...", "info")
		# Sum the frequency of the CDSs in each cluster to get the frequency per cluster
		frequency_in_genomes: Dict[str, int] = {repid: sum(cds_frequency[seqid] for seqid in members) for repid, members in clusters.items()}
		# Drop clusters with a frequency below the given threshold and add the corresponding CDS IDs to the dropped dict
		infrequent: List[str] = []
		excluded_clusters: List[str] = []
		for repid in clusters:
			if frequency_in_genomes[repid] <= constants[2]:
				infrequent.extend(clusters[repid])
				excluded_clusters.append(repid)
		# Exclude clusters
		for repid in excluded_clusters:
			del clusters[repid]

		# Add seqids excluded based on cluster frequency on genomes
		for seqid in infrequent:
			excluded.setdefault(seqid, []).append("Infrequent")

		pf.print_message(f"Excluded {len(excluded_clusters)} clusters (a total of {len(infrequent)} CDSs).")
		pf.print_message(f"{len(clusters)} clusters remain after filtering based on CDS frequency.", "info")

		# Create the files needed to run BLAST
		pf.print_message("Creating input files for BLAST...", "info")
		loci_files, concatenated_files = cof.prepare_cluster_blast_infiles(blast_inputs, clusters, cds_sequences, protein_sequences, blastdb_aliastool_exec)

	if run_mode == 'schema':
		# Check if schemas have loci with the same identifiers
		if len(input_schemas) > 1:
			common_loci = determine_common_loci_ids(input_schemas)
			if len(common_loci) > 0:
				pf.print_message(f"Found a total of {len(common_loci)} loci identifiers shared between different schemas.", "info")
				pf.print_message("Please make sure that loci in different schemas have different identifiers.", "info")
				sys.exit(0)

		# Calculate the allele call class counts
		input_class_counts = []
		for ad in allelecall_directories:
			class_counts = compute_class_counts(ad)
			input_class_counts.append(class_counts)

		# Merge dictionaries with class counts into a single dictionary with the class counts for all loci
		loci_class_counts = {}
		for cc in input_class_counts:
			loci_class_counts = loci_class_counts | cc

		# Exclude loci based on their frequency on the genomes and the fraction of special classifications
		for locus, counts in loci_class_counts.items():
			if counts[2] <= constants[2]:
				excluded.setdefault(locus, []).append("Infrequent")
			if counts[1] >= constants[3]:
				excluded.setdefault(locus, []).append("Ambiguous")

		frequency_in_genomes = {locus: counts[2] for locus, counts in loci_class_counts.items()}

		# Copy FASTA files from all schemas into the same directory
		temp_schema = ff.join_paths(processed_indata, ["merged_schema"])
		ff.create_directory(temp_schema)
		temp_schema_short = ff.join_paths(temp_schema, ["short"])
		ff.create_directory(temp_schema_short)
		pf.print_message(f"Copying FASTA files from all schemas to {temp_schema_short}...", "info")
		for schema in input_schemas:
			pf.print_message(f'Copying FASTA files from: {schema}', 'info')
			schema_short = ff.join_paths(schema, ["short"])
			# List FASTA files in the "short" directory
			schema_short_files = ff.get_paths_in_directory_with_suffix(schema_short, ".fasta")
			for file in schema_short_files:
				locus_id = ff.file_basename(file).rsplit('_short', 1)[0]
				if locus_id not in excluded:
					shutil.copy(file, temp_schema_short)
				else:
					pf.print_message(f"File {file} was excluded because of the following reasons: {excluded[locus_id]}.", "info")

		pf.print_message("Creating input files for BLAST...", "info")
		loci_files, concatenated_files = cof.prepare_loci_blast_infiles(temp_schema, blast_inputs, constants[6], constants[7], blastdb_aliastool_exec)

	#####################################
	# Main part common to all run modes #
	#####################################

	# Write file with the list of excluded CDSs/loci
	excluded_outfile = ff.join_paths(output_directory, [ct.EXCLUDED_FILENAME])
	excluded_outlines = [f"{seqid}: {', '.join(reason)}" for seqid, reason in excluded.items()]
	excluded_outtext = "\n".join(excluded_outlines)
	with open(excluded_outfile, "w") as outfile:
		outfile.write(excluded_outtext+"\n")

	# Create output folder to store BLASTp results
	blast_output: str = os.path.join(output_directory, '3_BLAST_Results')
	ff.create_directory(blast_output)

	# Create BLASTp database
	pf.print_message(f"Creating BLASTp database for {concatenated_files[1]}...", "info")
	blastp_db_directory: str = ff.join_paths(blast_inputs, ['BLASTp_db'])
	ff.create_directory(blastp_db_directory)
	blastp_db_path: str = ff.join_paths(blastp_db_directory, ['BLASTp_db'])
	bf.make_blast_db(makeblastdb_exec, concatenated_files[1], blastp_db_path, 'prot')

	# Calculate BLASTp self-score for all cluster/locus representatives
	self_blastp_inputs = {locus: paths[1] for locus, paths in loci_files.items()}
	self_blastp_outdir = ff.join_paths(blast_output, ["self_scores"])
	ff.create_directory(self_blastp_outdir)
	self_score_dict: Dict[str, float] = bf.calculate_self_score(self_blastp_inputs, blastp_exec, self_blastp_outdir, cpu)

	# Run BLASTp to align each representative protein against all other representative proteins
	pf.print_message("Running BLASTp...", "info")
	blastp_inputs: Dict[str, List[str]] = {locus: [paths[1], paths[3]] for locus, paths in loci_files.items()}
	blastp_outdir = ff.join_paths(blast_output, ["BLASTp_results"])
	ff.create_directory(blastp_outdir)
	# Allow multiple High-Scoring Segment Pairs to determine the global aligned fraction
	# Define a value for max_targets that is high enough to report all/most relevant alignments
	blastp_outfiles = bf.run_blast_operations(blastp_inputs, blastp_outdir, blastp_db_path, blastp_exec, cpu, max_hsps=5, max_targets=100)

	# Create BLASTn database
	blastn_db_directory: str = ff.join_paths(blast_inputs, ['BLASTn_db'])
	ff.create_directory(blastn_db_directory)
	blastn_db_path: str = ff.join_paths(blastn_db_directory, ['BLASTn_db'])
	bf.make_blast_db(makeblastdb_exec, concatenated_files[0], blastn_db_path, 'nucl')

	# Run BLASTn
	# Only using representative alleles, so running for all loci should not be a problem
	pf.print_message("Running BLASTn...", "info")
	blastn_inputs: Dict[str, List[str]] = {locus: [paths[0], paths[3]] for locus, paths in loci_files.items()}
	blastn_outdir = ff.join_paths(blast_output, ["BLASTn_results"])
	ff.create_directory(blastn_outdir)
	blastn_outfiles = bf.run_blast_operations(blastn_inputs, blastn_outdir, blastn_db_path, blastn_exec, cpu, max_hsps=5, max_targets=100)

	# Process BLAST results to get global and local stats
	blast_results_dict = {}
	for i, file in enumerate(blastp_outfiles):
		# Import BLASTp results
		blastp_data = read_blast_results(file)

		# Import BLASTn results
		blastn_file = blastn_outfiles[i]
		blastn_data = read_blast_results(blastn_file)

		# No matches with both BLASTp and BLASTn
		if not blastp_data and not blastn_data:
			pf.print_message(f"No BLASTp and BLASTn matches for {file}.", "info")
			continue

		# Merge BLASTp and BLASTn pairs
		blast_pairs = set.union(set(blastn_data.keys()), set(blastp_data.keys()))

		# Process BLAST data to get relevant values for each QS pair
		for qs_pair in blast_pairs:
			query, subject = qs_pair
			blastp_matches = blastp_data.get(qs_pair)
			blastn_matches = blastn_data.get(qs_pair)
			# Determine and add global values
			if qs_pair not in blast_results_dict and (subject, query) not in blast_results_dict:
				global_data = compute_global_stats(query, subject, frequency_in_genomes, blastp_matches, blastn_matches)					
				# Create QS pair entry
				blast_results_dict.setdefault(qs_pair, [[[],[]], [[],[]], global_data])

			# Get BLASTp data
			if blastp_matches:
				for m in blastp_matches:
					match_stats = compute_local_stats(m, self_score_dict[query])
					if qs_pair in blast_results_dict:
						blast_results_dict[qs_pair][0][0].append(match_stats)
					elif (subject, query) in blast_results_dict:
						blast_results_dict[(subject, query)][1][0].append(match_stats)

			# Get BLASTn data
			if blastn_matches:
				for m in blastn_matches:
					match_stats = compute_local_stats(m, None)
					if qs_pair in blast_results_dict:
						blast_results_dict[qs_pair][0][1].append(match_stats)
					elif (subject, query) in blast_results_dict:
						blast_results_dict[(subject, query)][1][1].append(match_stats)

	# Compute stat values evaluated for class assignment
	# Compute the total alignment length for each QS pair by merging the HSPs if there are multiple HSPs for the same QS pair
	# At this stage, the results are still structured as QS pairs of representative alleles
	# It is necessary to merge the results by locus at a later stage
	for qs_pair, match_data in blast_results_dict.items():
		# Merge BLASTp aligned intervals
		query_length: int = int(match_data[2][0])
		subject_length: int = int(match_data[2][1])
		# Query to subject alignments
		# Query
		class_stats = compute_class_stats(match_data[0][0], query_length, subject_length)
		blast_results_dict[qs_pair][0].append(class_stats)
		# Subject
		class_stats = compute_class_stats(match_data[1][0], query_length, subject_length)
		blast_results_dict[qs_pair][1].append(class_stats)

		# Merge BLASTn aligned intervals
		# Query to subject alignments
		# Query
		class_stats = compute_class_stats(match_data[0][1], query_length, subject_length)
		blast_results_dict[qs_pair][0].append(class_stats)
		# Subject
		class_stats = compute_class_stats(match_data[1][1], query_length, subject_length)
		blast_results_dict[qs_pair][1].append(class_stats)

	# Assign classes to all matches
	for qs_pair, match_data in blast_results_dict.items():
		query_freq = match_data[2][2]
		subject_freq = match_data[2][3]
		frequency_ratio = match_data[2][4]

		# Get data for QS matches
		qs_data = match_data[0][2]
		# Get data for Subject-Query matches
		sq_data = match_data[1][2]

		# Classify QS matches
		assigned_class = assign_class(qs_data, constants[0], constants[1], constants[8], frequency_ratio)
		blast_results_dict[qs_pair][0].append(assigned_class)
		# Classify Subject-Query matches
		assigned_class = assign_class(sq_data, constants[0], constants[1], constants[8], frequency_ratio)
		blast_results_dict[qs_pair][1].append(assigned_class)

	# Write TSV file with data for all matches
	match_data_outfile = ff.join_paths(output_directory, [ct.MATCHES_FILENAME])
	pf.print_message(f"Saving matches data to {match_data_outfile}...", "info")
	total_matches = write_matches_data(blast_results_dict, match_data_outfile)
	pf.print_message(f"Saved data for {total_matches} matches.", "info")

##### Am I selecting the top class per locus??? Or am I just using the last match?

	# Get all classes assigned to each sequence
	pf.print_message("Assigning actions based on assigned classes...", "info")
	assigned_classes = {}
	for qs_pair, match_data in blast_results_dict.items():
		query_class = match_data[0][-1]
		query_frequency = match_data[2][2]
		subject_class = match_data[1][-1]
		subject_frequency = match_data[2][3]
		# Need to group assigned classes for each locus if running in modes "schema" or "schema-vs-schema"
		if run_mode == "cds":
			# When running in the "cds" mode
			assigned_classes.setdefault(qs_pair[0], []).append([query_class, query_frequency, subject_frequency])
			assigned_classes.setdefault(qs_pair[1], []).append([subject_class, subject_frequency, query_frequency])
		else:
			# When running in the "schemas" mode
			query_id = (qs_pair[0]).rsplit('_', 1)[0]
			subject_id = (qs_pair[1]).rsplit('_', 1)[0]
			assigned_classes.setdefault(query_id, []).append([query_class, query_frequency, subject_frequency])
			assigned_classes.setdefault(subject_id, []).append([subject_class, subject_frequency, query_frequency])

	# Sort the results for each query by class
	class_order = ct.CLASSES_OUTCOMES
	# Assign an integer value to each class based on order
	class_order = {value: index for index, value in enumerate(class_order)}
	# Sort list of assigned classes
	actions = {}
	for seqid, classes in assigned_classes.items():
		assigned_action = assign_action(classes, class_order)
		actions[seqid] = assigned_action

	# Use all Quey-Subject pairs to create a graph and identify connected components
	groups, groups_seqids = determine_groups(blast_results_dict.keys(), actions, run_mode)

	# Add remaining representative seqids as Add and assign class 7
	if run_mode == "cds":
		representative_seqids = clusters.keys()
	# Add loci that had no matches
	else:
		representative_seqids = loci_files.keys()

	singletons = [seqid for seqid in representative_seqids if seqid not in groups_seqids]
	pf.print_message(f"{len(singletons)} representative CDSs/loci had no matches with any sequence.", "info")
	for seqid in singletons:
		groups.append([(seqid, "Add", "7")])

	# Add excluded representative seqids as Drop and assign class 8
	for seqid in excluded:
		groups.append([(seqid, "Drop", "8")])

	# Write main output file
	recommendations_file = ff.join_paths(output_directory, ["recommendations.tsv"])
	total_groups, total_recommendations = write_recommendations(groups, recommendations_file)
	pf.print_message(f"Saved recommendations for {total_recommendations} sequences in {total_groups} groups to {recommendations_file}.", "info")

	# Print the classification results
	# Count Action-Class pairs
	ac_counts = count_action_class_pairs(groups)
	# Sort Action-Class counts based on class priority
	sorted_counts = sorted(ac_counts.items(), key=lambda x: class_order.get(x[0][1]))
	for scount in sorted_counts:
		pf.print_message(f"{scount[1]} representative sequences were classified as {scount[0][1]} and with an action of {scount[0][0]}.", "info")

	# Need to create FASTA files with the set of representative alleles listed in the file with recommendations
	if run_mode == "cds":
		# Create folder to store cluster FASTA files
		cluster_fasta_dir = ff.join_paths(output_directory, ["groups_fastas"])
		ff.create_directory(cluster_fasta_dir)
		for repid, seqids in clusters.items():
			cluster_outfile = ff.join_paths(cluster_fasta_dir, [f"{repid}.fasta"])
			# Get the sequence of the representative allele
			cluster_sequences = [f">{repid}_{i+1}\n{cds_sequences[seqid]}" for i, seqid in enumerate(seqids)]
			cluster_outtext = "\n".join(cluster_sequences)
			with open(cluster_outfile, "w") as outfile:
				outfile.write(cluster_outtext+"\n")

	# Append loci annotations to the recommendations
	annotated_recommendations = os.path.join(output_directory, "recommendations_annotated.tsv")
	if annotations:
		pf.print_message(f"Appending annotations in {annotations} to file with recommendations...", "info")
		files = [recommendations_file, annotations]
		consolidated_annotations: str = consolidate.consolidate_annotations(files, False, annotated_recommendations)
		pf.print_message(f"Saved annotated recommendations to {annotated_recommendations}.", "info")
		# Remove non-annotated recommendations file
		os.remove(recommendations_file)

	# Clean up temporary files
	if not no_cleanup:
		pf.print_message("Cleaning up temporary files...", "info")
		# Remove temporary files
		shutil.rmtree(processed_indata)
		shutil.rmtree(blast_inputs)
		shutil.rmtree(blast_output)


def main(input_schemas: List[str], output_directory: str, allelecall_directories: List[str], annotations: str,
		 alignment_ratio_threshold: float, pident_threshold: float, clustering_sim_threshold: float,
		 clustering_cov_threshold:float, genome_presence: int, special_classifications: float, absolute_size: int,
		 translation_table: int, bsr: float, size_ratio: float, run_mode: str, cpu: int, no_cleanup: bool) -> None:
	"""
	Main function to RefineSchema module.

	Parameters
	----------
	input_schemas : List[str]
		Path to the schema directory.
	output_directory : str
		Path to the output directory.
	allelecall_directories : List[str]
		Path to the allele call directory.
	annotations : str
		Path to a TSV file containing loci annotations.
	alignment_ratio_threshold : float
		Threshold for alignment ratio.
	pident_threshold : float
		Threshold for percentage identity.
	clustering_sim_threshold : float
		Similarity threshold for clustering.
	clustering_cov_threshold : float
		Coverage threshold for clustering.
	genome_presence : int
		Minimum genome presence required.
	absolute_size : int
		Absolute size threshold.
	translation_table : int
		Genetic code used for translation.
	bsr : float
		BLAST Score Ratio value.
	size_ratio : float
		Size ratio threshold.
	run_mode : str
		Mode of running the process.
	cpu : int
		Number of CPU cores to use.
	no_cleanup : bool
		Flag to indicate whether to clean up temporary files.

	Returns
	-------
	None
	"""
	# Put all constants in a list to decrease number of variables used around
	constants: List[Any] = [alignment_ratio_threshold, 
							pident_threshold,
							genome_presence,
							special_classifications,
							clustering_sim_threshold,
							clustering_cov_threshold,
							absolute_size,
							translation_table,
							bsr,
							size_ratio]

	refine_schema(input_schemas,
				  allelecall_directories,
				  output_directory,
				  annotations,
				  constants,
				  run_mode,
				  cpu,
				  no_cleanup)
